import { SeasonData } from './types';

export const SEASONS: SeasonData[] = [
  {
    id: 'spring',
    title: 'Spring',
    chineseTitle: '春 · 生机',
    description: 'The mountains wake up. Delicate blossoms and fresh greenery breathe life back into the Jinshanling landscape.',
    color: '#5A5A40',
    heroImage: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/hero.jpg',
    gallery: [
      { id: 'sp1', title: 'Mountain Mist', location: 'Valley Road', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/1.jpg' },
      { id: 'sp2', title: 'First Bloom', location: 'Community Garden', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/2.jpg' },
      { id: 'sp4', title: 'Verdant Peaks', location: 'Observation Deck', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/4.jpg' },
      { id: 'sp5', title: 'Spring Serenity', location: 'Mountain Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/5.jpg' },
      { id: 'sp6', title: 'Blossom Trail', location: 'East Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/6.jpg' },
      { id: 'sp7', title: 'Spring Awakening', location: 'Mountain Slope', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/7.jpg' },
      { id: 'sp8', title: 'Floral Valley', location: 'South Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/8.jpg' },
      { id: 'sp9', title: 'Morning Dew', location: 'Forest Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/spring/9.jpg' },
    ]
  },
  {
    id: 'summer',
    title: 'Summer',
    chineseTitle: '夏 · 繁茂',
    description: 'Deep greens and golden sunlight. The community thrives under the warmth of the mountain sun.',
    color: '#2C4A3E',
    heroImage: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/hero.jpg',
    gallery: [
      { id: 'su1', title: 'Golden Hour', location: 'The Plaza', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/1.jpg' },
      { id: 'su2', title: 'Forest Canopy', location: 'Pine Forest', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/2.jpg' },
      { id: 'su3', title: 'Summer Breeze', location: 'Terrace', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/3.jpg' },
      { id: 'su4', title: 'Mountain Stream', location: 'North Creek', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/4.jpg' },
      { id: 'su5', title: 'Summer Peak', location: 'Jinshanling', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/5.jpg' },
      { id: 'su6', title: 'Lush Valley', location: 'Green Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/6.jpg' },
      { id: 'su7', title: 'Summer Twilight', location: 'Sunset Point', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/7.jpg' },
      { id: 'su8', title: 'Mountain Path', location: 'West Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/8.jpg' },
      { id: 'su9', title: 'Forest Light', location: 'Pine Grove', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/9.jpg' },
      { id: 'su10', title: 'Summer Horizon', location: 'Peak View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/10.jpg' },
      { id: 'su11', title: 'Mountain Mist', location: 'Valley Road', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/11.jpg' },
      { id: 'su12', title: 'Summer Stream', location: 'River Bank', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/12.jpg' },
      { id: 'su13', title: 'Green Peaks', location: 'East Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/13.jpg' },
      { id: 'su14', title: 'Summer Serenity', location: 'Mountain Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/14.jpg' },
      { id: 'su15', title: 'Summer Bloom', location: 'Community Garden', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/15.jpg' },
      { id: 'su16', title: 'Golden Ridge', location: 'Observation Deck', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/16.jpg' },
      { id: 'su17', title: 'Summer Valley', location: 'Hiking Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/17.jpg' },
      { id: 'su18', title: 'Lush Peak', location: 'Summit View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/18.jpg' },
      { id: 'su19', title: 'Summer Trail', location: 'Forest Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/19.jpg' },
      { id: 'su20', title: 'Mountain Lake', location: 'Blue Water', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/20.jpg' },
      { id: 'su21', title: 'Summer Meadow', location: 'Green Field', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/21.jpg' },
      { id: 'su22', title: 'Peak Sunset', location: 'High Point', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/22.jpg' },
      { id: 'su23', title: 'Summer Forest', location: 'North Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/23.jpg' },
      { id: 'su24', title: 'Mountain View', location: 'Summit Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/24.jpg' },
      { id: 'su25', title: 'Golden Valley', location: 'East Slope', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/25.jpg' },
      { id: 'su26', title: 'Summer Stream', location: 'Creek Side', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/26.jpg' },
      { id: 'su27', title: 'Lush Meadow', location: 'Green Valley', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/summer/27.jpg' },
    ]
  },
  {
    id: 'autumn',
    title: 'Autumn',
    chineseTitle: '秋 · 绚烂',
    description: 'A masterpiece of fire and gold. The mountains transform into a tapestry of brilliant colors.',
    color: '#8B4513',
    heroImage: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/hero.jpg',
    gallery: [
      { id: 'au1', title: 'Autumn Gold', location: 'Maple Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/1.jpg' },
      { id: 'au2', title: 'Harvest Season', location: 'Mountain Valley', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/2.jpg' },
      { id: 'au3', title: 'Crimson Forest', location: 'Ridge View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/3.jpg' },
      { id: 'au4', title: 'Golden Afternoon', location: 'Pine Grove', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/4.jpg' },
      { id: 'au5', title: 'Autumn Mist', location: 'Valley Road', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/5.jpg' },
      { id: 'au6', title: 'Golden Ridge', location: 'Summit View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/6.jpg' },
      { id: 'au7', title: 'Crimson Valley', location: 'Hiking Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/7.jpg' },
      { id: 'au8', title: 'Autumn Serenity', location: 'Mountain Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/8.jpg' },
      { id: 'au9', title: 'Golden Leaves', location: 'Forest Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/9.jpg' },
      { id: 'au10', title: 'Autumn Peak', location: 'Summit Point', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/10.jpg' },
      { id: 'au11', title: 'Crimson Ridge', location: 'Mountain Pass', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/11.jpg' },
      { id: 'au12', title: 'Harvest Glow', location: 'Valley View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/12.jpg' },
      { id: 'au13', title: 'Autumn Trail', location: 'Forest Path', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/13.jpg' },
      { id: 'au14', title: 'Mountain Mist', location: 'Valley Road', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/14.jpg' },
      { id: 'au15', title: 'Golden Bloom', location: 'Community Garden', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/15.jpg' },
      { id: 'au16', title: 'Crimson Ridge', location: 'Observation Deck', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/16.jpg' },
      { id: 'au17', title: 'Autumn Valley', location: 'Hiking Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/17.jpg' },
      { id: 'au18', title: 'Autumn Reflection', location: 'Mirror Lake', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/18.jpg' },
      { id: 'au19', title: 'Golden Canopy', location: 'Forest Edge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/19.jpg' },
      { id: 'au20', title: 'Crimson Peak', location: 'North Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/autumn/20.jpg' },
    ]
  },
  {
    id: 'winter',
    title: 'Winter',
    chineseTitle: '冬 · 寂静',
    description: 'Pure white silence. The architecture stands in stark, beautiful contrast against the snow-covered peaks.',
    color: '#4A5568',
    heroImage: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/hero.jpg',
    gallery: [
      { id: 'wi1', title: 'Winter Silence', location: 'Main Entrance', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/1.jpg' },
      { id: 'wi2', title: 'Snow Peak', location: 'Summit View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/2.jpg' },
      { id: 'wi3', title: 'Frozen Ridge', location: 'North Slope', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/3.jpg' },
      { id: 'wi4', title: 'Winter Morning', location: 'Valley Road', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/4.jpg' },
      { id: 'wi5', title: 'Snow Forest', location: 'Pine Grove', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/5.jpg' },
      { id: 'wi6', title: 'Frozen Stream', location: 'River Bank', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/6.jpg' },
      { id: 'wi7', title: 'Winter Light', location: 'East Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/7.jpg' },
      { id: 'wi8', title: 'Snow Path', location: 'West Trail', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/8.jpg' },
      { id: 'wi9', title: 'Winter Horizon', location: 'Peak View', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/9.jpg' },
      { id: 'wi10', title: 'Frozen Valley', location: 'South Ridge', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/10.jpg' },
      { id: 'wi11', title: 'Winter Mist', location: 'North Pass', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/11.jpg' },
      { id: 'wi12', title: 'Snow Meadow', location: 'Green Field', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/12.jpg' },
      { id: 'wi13', title: 'Winter Serenity', location: 'Chapel', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/13.jpg' },
      { id: 'wi14', title: 'Frozen Lake', location: 'South Pond', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/14.jpg' },
      { id: 'wi15', title: 'Winter Twilight', location: 'Sunset Point', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/15.jpg' },
      { id: 'wi16', title: 'Snow Ridge', location: 'Observation Deck', url: 'https://aranya-photography.oss-cn-beijing.aliyuncs.com/winter/16.jpg' },
    ]
  }
];
